[project]
name = "string-to-number"
version = "0.1.0"
description = "Simple string to number converter with Streamlit interface"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
]
